env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - airbnb-base
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
settings: 
    react: 
        version: detect
plugins:
  - react
rules: 
  no-console: 0
  import/extensions: 0 
  no-param-reassign: 0
  no-unused-expressions: 0
  import/no-unresolved: 0
  default-param-last: 0
  no-shadow: 0
